### ISSUE TITLE
Setting taxonID when mapping IDs (Uniprot)

### ISSUE THREAD

**Issue by poojaparameswaran99** [iquasere/UPIMAPI#11]
Hi, thank you for your detailed package. I am trying to convert Gene Name (from) -> Uniprot (to) but only for a specific taxonomy. However, in the POST request, I am not sure the keyword to filter specifically for mouse (taxonId = 10090). Have you had any experience? 
```
def submit_id_mapping(from_db, to_db, ids):
    request = requests.post(
        f"{API_URL}/idmapping/run",
        data={'taxonId': 10090, "from": from_db, "to": to_db, "ids": ",".join(ids),
              }
    )
    check_response(request)
    return request.json()["jobId"]
````

**Comment by iquasere** [comment]
Never have tried that... But you should contact UniProt directly about it at https://www.uniprot.org/contact

They are quick to answer
