### ISSUE TITLE
Error fetching UniProt

### ISSUE THREAD

**Issue by apaytuvi** [iquasere/UPIMAPI#2]
Dear authors,

Thank you for this useful tool called UPIMAPI. Maybe because of the update on the ID mapping from UniProt recently, but UPIMAPI is giving me error 405 at the time to call the UniProt API.

Best,

**Comment by iquasere** [comment]
Hey there! Yes, the updates on their API have broken UPIMAPI 1.7. I have been in contact with them for the past two days, and already have a group of alterations that should restore UPIMAPI's functionality
