### ISSUE TITLE
Question regarding the apt-get packages

### ISSUE THREAD

**Issue by sturne29** [iquasere/UPIMAPI#5]
Apologies if this is a very easy fix and I'm unaware of it - I am on a system (shared computing environment) that does not support apt-get. Is there a way to install those packages without using apt-get?

**Comment by iquasere** [comment]
Can you use ```apt```? ```dpkg```? ```yum```? What operating system are you using?

**Comment by iquasere** [comment]
Can you use ```apt```? ```dpkg```? ```yum```? What operating system are you using?

**Comment by sturne29** [comment]
I'm on CentOS 7, and do have yum. Unfortunately I've been unable to use yum in the past, and haven't been able to solve the problem (which I understand is beyond the scope of this question). If that means I can't use the program, I understand - just wondering if there were any other workaround.

**Comment by iquasere** [comment]
Do you have access to dpkg? apt-get is just a wrapper of that, if you can use dpkg it might work!

**Comment by sturne29** [comment]
Unfortunately I don't. (Thank you again for your responsiveness and help -
I really appreciate it!)

On Tue, Oct 25, 2022 at 3:23 PM João Sequeira ***@***.***>
wrote:

> Do you have access to dpkg? apt-get is just a wrapper of that, if you can
> use dpkg it might work!
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiquasere%2FUPIMAPI%2Fissues%2F5%23issuecomment-1291093521&data=05%7C01%7Csturne29%40groute.uic.edu%7Cd12f0c8435054611a71408dab6c6bb24%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638023261912904399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NTUuSg8iE0ABx6OQBfTMdoghxorANpeqGC8wI1VzqvM%3D&reserved=0>,
> or unsubscribe
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEZPVV62NZX2Y55NWZOA3FTWFA6SZANCNFSM6AAAAAAROETIWI&data=05%7C01%7Csturne29%40groute.uic.edu%7Cd12f0c8435054611a71408dab6c6bb24%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638023261912904399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zlZuZoZ7lrTuuRTHLrsbRyB1lgnxhD5zoXeqr%2Be91kM%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Sarah Turner
Graduate Student, Poretsky Lab
University of Illinois at Chicago
Department of Biological Sciences
Ecology and Evolution

**Comment by iquasere** [comment]
Then I'm out of options... UPIMAPI didn't require those packages before, but now that UniProt's website is built in some JS framework (I believe React), UPIMAPI requires those packages for webscraping, and conda doesn't provide them. If you do manage to find a way to install them with conda, please let me know!

For now I'll close this, as it is not an issue with UPIMAPI.

**Comment by iquasere** [comment]
One alternative solution I thought about is docker. If you can run a docker container in your system, you should have ```apt``` available there. If you want instructions on how to do this, don't hesitate asking
