### ISSUE TITLE
Obsolete GO terms are not being replaced

### ISSUE THREAD

**Issue by Maxim-Karpov** [iquasere/UPIMAPI#9]
Hello,

I found that UPIMAPI doesn't replace the obsolete GO terms (as per the go-basic.obo file) with the updated GO terms. For example the term GO:0000469 is now replicable by GO:0006364. This has caused me issues with a GO enrichment analysis downstream. Am writing this as a suggestion for improvement of UPIMAPI.

Thanks,
Maxim

**Comment by iquasere** [comment]
Thank you for the suggestion, seems something very useful to integrate in UPIMAPI. I'll have to do a parser for [the file in question](http://current.geneontology.org/ontology/go-basic.obo), but seems doable.

Next version of UPIMAPI should include this. Maybe until the end of the week I'll release that. If you already have an idea of how to tackle this issue (e.g. already have a parser for the go-basic file) don't hesitate [making a pull request](https://github.com/iquasere/UPIMAPI/pulls).

**Comment by iquasere** [comment]
@Maxim-Karpov , what do you suggest be done when the entry is like this?
```
[Term]
id: GO:0000008
name: obsolete thioredoxin
namespace: molecular_function
alt_id: GO:0000013
def: "OBSOLETE. A small disulfide-containing redox protein that serves as a general protein disulfide oxidoreductase. Interacts with a broad range of proteins by a redox mechanism, based on the reversible oxidation of 2 cysteine thiol groups to a disulfide, accompanied by the transfer of 2 electrons and 2 protons. The net result is the covalent interconversion of a disulfide and a dithiol." [GOC:kd]
comment: This term was made obsolete because it represents gene products.
synonym: "thioredoxin" EXACT []
is_obsolete: true
consider: GO:0003756
consider: GO:0015036
```

**Comment by iquasere** [comment]
@Maxim-Karpov , do you know the difference between `replaced_by` and `consider`? E.g.,
```
[Term]
id: GO:0003776
name: obsolete muscle motor activity
namespace: molecular_function
def: "OBSOLETE. (Was not defined before being made obsolete)." [GOC:mah]
comment: This term was made obsolete because it includes anatomy information.
synonym: "muscle motor activity" EXACT []
is_obsolete: true
replaced_by: GO:0000146
consider: GO:0006936
consider: GO:0043292
```

**Comment by iquasere** [comment]
This is much more complicated than I antecipated. For example, the term `GO:0003763 - obsolete chaperonin ATPase activity` is replaced by `GO:0016887 - ATP hydrolysis activity`, and even though the former may be considered a specialized function of the latter, they are not interchangeable. I think it might be best to inform UniProt of this, so they may update their databases and cross-references. In the meantime, I built a [TSV version](https://github.com/iquasere/UPIMAPI/files/12714286/go-basic.tsv.txt) from the OBO file that you might find helpful. You may adapt it to your specific needs, by cross-referencing it with the results from UPIMAPI, and obtaining the updated GOs.

If you would like to obtain the TSV for future versions, just run this awk command:
```
awk 'BEGIN {print "id\treplaced_by\tconsider"}
/^\[Term\]/{if(is_obsolete) print id"\t"replaced_by"\t"consider; is_obsolete=id=replaced_by=consider=""; next}
/^id:/{id=$2}
/^is_obsolete: true/{is_obsolete=1}
/^replaced_by:/{replaced_by=replaced_by ? replaced_by";"$2 : $2}
/^consider:/{consider=consider ? consider";"$2 : $2}' go-basic.obo > go-basic.tsv
```
